### ISSUE TITLE
Feature Request: DotBoarderColor

### ISSUE THREAD

**Issue by Edgaras91** [skordesign/SkorXam.Pin#1]
Hi,

Your red dots have a constant red frame and can't find a way to change that.
I can change the fill color with "DotColor", but not the frame.

Please add something like .DotBoarderColor.

Also, I suggest listing properties on your README.md

**Comment by skordesign** [comment]
Frame color? Sorry, I don't get it, you mean the background color of frame contains dots?

**Comment by Edgaras91** [comment]
> 
> 
> Frame color? Sorry, I don't get it, you mean the background color of the frame contains dots?

No,

If the page color is black, and DotColor is black, you get this:

![image](https://user-images.githubusercontent.com/32236075/60903232-d841cc00-a268-11e9-8102-c82058aade64.png)

the "frame"/"border" is always red

**Comment by skordesign** [comment]
Okay I got it, I'm working on it

**Comment by Edgaras91** [comment]
Let me know when I can update through NuGet.
Great solution otherwise!

**Comment by skordesign** [comment]
I've uploaded it to nuget, it's validating, maybe it takes a half hour.
You can check both of issues you've been created. If it works, please close the issues.

**Comment by Edgaras91** [comment]
Not fixed, the **DotBoarderColor** is not exposed in XAML.

**Comment by skordesign** [comment]
Have you check **DotBorderColor** properties, read **Properties** section on home page

**Comment by Edgaras91** [comment]
I think there is a bug in Visual Studio.
In C# I get .DotBorderColor, but in XAML I get 
`The property 'DotBorderColor' was not found in type 'PinView'.`

I have tested in an alternative way and it's working. Thank you.
