### ISSUE TITLE
Pin Frames set by ResourceDictionary for all frames, will take priority over color properties

### ISSUE THREAD

**Issue by Edgaras91** [skordesign/SkorXam.Pin#12]
Pin frames start filled on Android SDK 29+ with AndroidX - meaning not working on latest AndroidX libraries

![image](https://user-images.githubusercontent.com/32236075/101644859-9bfe3680-3a2d-11eb-936b-06324e3cbd3c.png)

**Comment by Edgaras91** [comment]
Wrong assumption on my end.
The issue was caused by Xamarin.Forms NuGet being on a different version.
Had to download the repo, add this project to the solution, and update its NuGet to match my solution's Xamarin.Forms version.

**Comment by Edgaras91** [comment]
Wrong again. A real bug is if you set the frame color in global style sheet, you will have this bug.
I did not find a solution, even by manually calling Fill() method after initialisation or OnAppearing overload.

```
    <Style TargetType="Frame">
        <Setter Property="Background" Value="White"/>
    </Style>
```

**Comment by skordesign** [comment]
Can you give me a repo that I can reproduce?

**Comment by Edgaras91** [comment]
sure, here you are:
https://github.com/Edgaras91/PinBug

**Comment by skordesign** [comment]
Hi @Edgaras91 ,
Can you just change ```<Setter Property="Background" Value="White"/>```  to  ```<Setter Property="BackgroundColor" Value="White"/>```. I can see the Background property overrides BackgroundColor property.

**Comment by Edgaras91** [comment]
Will try and get back here.

**Comment by Edgaras91** [comment]
Yup, that fixed it. I guess I didn't need to use `Background` after all, I needed to use `BackgroundColor`.

Thanks for checking it out!
