### ISSUE TITLE
[Bug] Dot corner radius is same as size

### ISSUE THREAD

**Issue by CameronMcDougall** [skordesign/SkorXam.Pin#3]
The dot corner radius is the same size as the height/width request as it currently uses DotSize. This causes iOS to have a diamond shape as the radius is the same as the height/width.

Can you add another property for the dot corner radius, please?

**Comment by skordesign** [comment]
I'll add it.

**Comment by skordesign** [comment]
I've added **DotCornerRadius** property, you can check it and if it works just close issue. Thanks.

**Comment by CameronMcDougall** [comment]
There's some weird behavior going on in iOS and i'm not sure why. It seems its something to do with the time of update? 

It seems like the frames don't work properly until the render method is called.
Before pressing a button with shadow:
https://imgur.com/a/srMoEg9

After pressing a button with shadow:
https://imgur.com/a/9vsmxv1
