### ISSUE TITLE
New Features Request: Button font size, Spacing between buttons, Button color opacity

### ISSUE THREAD

**Issue by Edgaras91** [skordesign/SkorXam.Pin#7]
Hi,

Really need these 3 features, for this to go to production:

- Button font size
- Spacing between buttons
- Button color opacity

Would really appreciate your help on this.

**Comment by skordesign** [comment]
Hi @Edgaras91 , I'll add it on this week.
Thank you.

**Comment by skordesign** [comment]
Hi @Edgaras91 , Button color opacity is not supported because I use default Xamarin.Forms button so can I add Button Opacity property instead?

**Comment by Edgaras91** [comment]
> 
> 
> Hi @Edgaras91 , Button color opacity is not supported because I use default Xamarin.Forms button so can I add Button Opacity property instead?

Sure, I think that would be fine. Again, much appreciated.

**Comment by skordesign** [comment]
I've added it. You can check it now.
Ps: Don't forget give a star if this repo is useful for you.

**Comment by Edgaras91** [comment]
Tested, works as expected, thanks.
