### ISSUE TITLE
DotEmptyColor not working

### ISSUE THREAD

**Issue by Edgaras91** [skordesign/SkorXam.Pin#8]
On the latest version (1.02) the DotEmptyColor is not working, tried setting it to "Red", stays white.

My Xaml:
`                <pin:PinView x:Name="pinView"  
                             VerticalOptions="FillAndExpand"
                             DotColor="White" 
                             DotEmptyColor="Red" 
                             DotBorderColor="White" 
                             HorizontalOptions="Fill"
                             PinChanged="PinView_PinChangedAsync"  
                             ButtonSize="80" 
                             ButtonCornerRadius="40" 
                             ButtonVerticalSpacing="30" 
                             ButtonHorizontalSpacing="30" 
                             ButtonColor="#193C7B" 
                             ButtonOpacity="0.8" 
                             ButtonFontsize="24" 
                             Spacing="36"
                             PinSubmitCommand="{Binding PinSubmitCommand}"
                             Pin="{Binding Pin}"
                             IsVisible="{Binding PinVisability, Mode=TwoWay}"/>`

**Comment by skordesign** [comment]
Ok I've saw the issue. Will fix it.

**Comment by skordesign** [comment]
Fixed.

**Comment by Edgaras91** [comment]
> 
> 
> Fixed.

That's great, thanks. Could you release a nuget for it?

**Comment by skordesign** [comment]
Done. You can get it now.
